### ISSUE TITLE
Cycle detection in DAGs is not working properly

### ISSUE THREAD

**Issue by tomasfabian** [hmdsefi/gograph#72]
Hello, the `gograph` library version 0.4.0 is returning an incorrect error message, "edges would create cycle" when calling `graph.AddEdge(gograph.NewVertex(2), gograph.NewVertex(3))`, even though no cycle is being created at this point. The cycle is created afterward. 

```go
graph := gograph.New[int](gograph.Directed(), gograph.Acyclic())

_, err := graph.AddEdge(gograph.NewVertex(1), gograph.NewVertex(2))
if err != nil {
}
_, err = graph.AddEdge(gograph.NewVertex(2), gograph.NewVertex(3))
if err != nil {
  // the error is reported here
}
_, err = graph.AddEdge(gograph.NewVertex(3), gograph.NewVertex(1))
if err != nil {
  // the error should be reported here instead
}
```

**Comment by tomasfabian** [comment]
I reviewed the unit tests and found that this approach works as intended. 
```go
graph := gograph.New[string](gograph.Directed(), gograph.Acyclic())

v1 := graph.AddVertexByLabel("1")
v2 := graph.AddVertexByLabel("2")
v3 := graph.AddVertexByLabel("3")

_, err := graph.AddEdge(v1, v2)
if err != nil {
}
_, err = graph.AddEdge(v2, v3)
if err != nil {
}
_, err = graph.AddEdge(v3, v1)
if err != nil {
  //the error is correctly reported here
}
```
Shouldn't both approaches produce the same behavior?

**Comment by hmdsefi** [comment]
@tomasfabian Thank you for reporting the issue. This example should be in the unit tests. I will check the issue.

**Comment by hmdsefi** [comment]
@tomasfabian You can use [v0.4.1](https://github.com/hmdsefi/gograph/releases/tag/v0.4.1) the issue is fixed in the new version.
